# Resolve react_native_pods.rb with node to allow for hoisting
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, '17.0'
prepare_react_native_project!
use_modular_headers!

use_frameworks!

project 'ReactAgentforce.xcodeproj'
target 'ReactAgentforce' do
  # CocoaPods Sources
  source 'https://github.com/livekit/podspecs.git'
  source 'https://cdn.cocoapods.org/'

  $config = use_native_modules!

  use_react_native!(
    :path => $config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  # ========================================
  # Agentforce SDK - Service Agent Mode
  # ========================================
  # Note: Service Agent does NOT require SalesforceMobileSDK
  
  $artifactory_url = 'https://rpm.repo.local.sfdc.net/artifactory/api/pods/cocoapods-mobe'
  
  # Core Agentforce SDK
  pod 'AgentforceSDK', '~> 14.8.4', :source => $artifactory_url
  pod 'AgentforceService', '~> 4.3.0', :source => $artifactory_url
  
  # Messaging Framework (binary)
  pod 'Messaging-InApp-Core', :podspec => './Frameworks/Messaging-InApp-Core/Messaging-InApp-Core-binary.podspec'
  
  # LiveKit for voice/video capabilities
  pod 'LiveKitClient'
  
  # Markdown rendering for rich text
  pod 'swift-markdown-ui', :git => 'https://git.soma.salesforce.com/iOS/swift-markdown-ui.git', :branch => 'main'
  pod 'cmark_gfm', :git => 'https://git.soma.salesforce.com/iOS/swift-markdown-ui.git', :branch => 'main'
  
  # Required Swift dependencies
  pod 'DequeModule'
  pod 'InternalCollectionsUtilities'
  pod 'OrderedCollections'

end

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNReanimated')
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set minimum deployment target for all pods
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      
      # Enable module stability
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      
      # Disable code signing for frameworks
      if defined?(target.product_type) && target.product_type == "com.apple.product-type.framework"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end

  # React Native post-install
  $config = use_native_modules!
  
  react_native_post_install(
    installer,
    $config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
end
