require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static

project 'ReactAgentforce.xcodeproj'
target 'ReactAgentforce' do
  source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
  source 'https://cdn.cocoapods.org/'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  # Agentforce SDK for Service Agent (lightweight - no Mobile SDK required)
  $artifactory_url = 'https://rpm.repo.local.sfdc.net/artifactory/api/pods/cocoapods-mobe'
  
  pod "AgentforceSDK", '~> 14.8.4', :source => $artifactory_url
  pod 'AgentforceService', '~> 4.3.0', :source => $artifactory_url

  # Force exact version match for binary framework compatibility
  pod 'Messaging-InApp-Core', :podspec => './Frameworks/Messaging-InApp-Core/Messaging-InApp-Core-binary.podspec'

  # swift-markdown-ui from git repository
  pod "swift-markdown-ui", :git => 'https://git.soma.salesforce.com/iOS/swift-markdown-ui.git', :branch => 'main'
  pod "cmark_gfm", :git => 'https://git.soma.salesforce.com/iOS/swift-markdown-ui.git', :branch => 'main'

  # Required dependencies for AgentforceSDK
  pod 'DequeModule'
  pod 'InternalCollectionsUtilities'
  pod 'OrderedCollections'

end

pre_install do |installer|
    installer.pod_targets.each do |pod|
        if pod.name.eql?('RNReanimated')
            def pod.build_type
                Pod::BuildType.static_library
            end
        end
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'

      # Fix FMDB SQLCipher compilation by adding SQLCipher header search path
      if target.name == 'FMDB'
        config.build_settings['HEADER_SEARCH_PATHS'] ||= ['$(inherited)']
        config.build_settings['HEADER_SEARCH_PATHS'] << 'SQLCipher/sqlcipher-ios-fips/SQLCipher.xcframework/ios-arm64/SQLCipher.framework/Headers/'
      end
    end
  end

  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  # Comment the following if you do not want the SDK to emit signpost events for instrumentation. Signposts are  enabled for non release version of the app.
  # signposts_post_install(installer) # Commented out - function not available without mobile SDK helper

  $config = use_native_modules!

  # React native post install
  react_native_post_install(
      installer,
      $config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
  )

  # Post-install hook - no mobile SDK specific setup needed
end
