//
//  SMIFormResultError.h
//  SMIClientCore
//
//  Created by Jeremy Wright on 2023-07-31.
//

#import <SMIClientCore/SMIFormResult.h>

NS_ASSUME_NONNULL_BEGIN

/// Represents a failed `SMIFormInputs` submission.
NS_SWIFT_NAME(FormErrorResult)
@protocol SMIFormErrorResult <SMIFormResult>

/// The list of errors generated by the `SMIFormResponseInputs` submission.
@property (nonatomic, readonly, strong) NSArray<NSError *> *errors;

@end

NS_ASSUME_NONNULL_END
